// Root layout for the app. Sets up global fonts, providers, header, footer, and main content area.
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ReactQueryProvider from "../providers/ReactQueryProvider";
import { CartProvider } from "@/context/CartContext";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the app (used by Next.js)
export const metadata: Metadata = {
  title: "Grocery Store",
  description: "Generated by create next app",
  openGraph: {
    title: "Grocery Store",
    description: "Built with Next.js, Tailwind, TypeScript, shadcn/ui",
    url: "https://notes-web-app-tan.vercel.app",
    siteName: "Grocery Store",
    images: [
      {
        url: "https://notes-web-app-tan.vercel.app/Grocery_Store_Titel_Picture.png",
        width: 1200,
        height: 630,
        alt: "Grocery Store Preview",
      },
    ],
    locale: "de_DE",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#AAB7BF] min-h-screen flex flex-col `}
      >
        {/* React Query, Auth, and Cart providers wrap the app */}
        <ReactQueryProvider>
          <AuthProvider>
            <CartProvider>
              {/* Global header */}
              <Header />
              {/* Main content */}
              <main className="">
                {children}
              </main>
              {/* Global footer */}
              <Footer />
            </CartProvider>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
